services:
  vision:
    build: 
      context: ./environment
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/workdir/src
      - ./data:/home/workdir/data
      - ./models:/home/workdir/models
      - ./environment/.env:/home/workdir/.env
    tty: true
    environment:
      - PYTHONPATH=/home/workdir/src
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
